# Generated by Django 4.0.1 on 2022-01-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizza_approved_pizzeria_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzeria',
            options={'ordering': ['owner'], 'verbose_name': 'Pizzeria', 'verbose_name_plural': 'Pizzerias'},
        ),
    ]
