# Generated by Django 4.0.1 on 2022-01-06 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_alter_pizzeria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pizza.pizzeria'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='thumbnail_url',
            field=models.URLField(default=''),
        ),
    ]
