# Generated by Django 4.0.1 on 2022-01-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_pizza_creator_pizza_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzeria',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
