# Generated by Django 4.0.1 on 2022-01-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_pizzeria_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='type',
            field=models.CharField(choices=[('CA', 'Carne'), ('VE', 'Vegetariana'), ('VG', 'Vegana')], default='', max_length=20),
        ),
    ]
