# Generated by Django 4.0.1 on 2022-01-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_pizza_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.CharField(choices=[('CA', 'Carne'), ('VE', 'Vegetariana'), ('VG', 'Vegana'), ('DC', 'Doce')], default='', max_length=20),
        ),
    ]
