# Generated by Django 4.0.1 on 2022-01-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0010_alter_pizza_description_alter_pizza_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='likes',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
