# Generated by Django 4.0.1 on 2022-01-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0012_remove_likes_dislike_dislikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislikes',
            old_name='ser',
            new_name='user',
        ),
    ]
