# Generated by Django 4.0.1 on 2022-01-12 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0014_remove_dislikes_dislike_remove_likes_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['creator', 'title'], 'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizzas'},
        ),
        migrations.AlterModelOptions(
            name='pizzeria',
            options={'ordering': ['name', 'owner'], 'verbose_name': 'Pizzeria', 'verbose_name_plural': 'Pizzerias'},
        ),
    ]
