# Generated by Django 4.0.1 on 2022-01-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_email_alter_userprofile_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome de Usuário'),
        ),
    ]
